server:
    port: ${PORT}
postgres:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    db_name: ${POSTGRES_DB_NAME}
    ssl_mode: ${POSTGRES_SSL_MODE}